const jokes = [
  "Why did the salamander go to Hollywood? To make newt movies!",
  "Did you hear the one about the New York Jets cocktail? Drink two of them and you forget what Joe Namath.",
  "Why did the veterinarian prescribe birth-control pills for dogs? It's part of an anti-litter campaign.",
  "Why don't pirates take a shower before they walk the plank? They just wash up on shore.",
  "On what grounds did the police arrest the devil? They got him on possession.",
  "How many telemarketers does it take to change a lightbulb? Only one, but he has to do it while you are eating dinner.",
  "What did one fish in a tank say to the other fish in the tank? 'Do you know how to drive this thing?'",
  "What do rich people say when they tickle babies? 'Gucci, Gucci, goo.'",
  "How many therapists does it take to change a lightbulb? Only one, but the lightbulb has to want to change.",
  "Why don't anteaters ever get sick? Their anty-bodies keep them healthy.",
  "How many gorillas does it take to change a lightbulb? Just one … but it takes a whole lot of lightbulbs.",
  "Who was the roundest knight in King Arthur's court? Sir Cumference.",
  "Why do cemeteries have fences around them? Because everyone's dying to get in.",
  "How many optometrists does it take to change a lightbulb? Is it one or two? One … or two?",
  "What do you give a man who has everything? Penicillin.",
  "What kind of felines can bowl? Alley cats.",
  "Why did the man bring his watch to the bank? He wanted to save time.",
  "What's the difference between a hippo and a Zippo? One weighs a ton, and the other is a little lighter.",
  "Did you hear about the guy who got the left side of his body amputated? He's all right now.",
  "What do you call a fake dad? A faux pas.",
  "Why do dogs float in water? Because they're good buoys.",
  "What should you do if your puppy isn't feeling well? Take him to the dog-tor.",
  "Why couldn't the lifeguard rescue the hippie? Because he was too far out, man.",
  "Where do penguins go to vote? The North Poll.",
  "What do you call a girl with no eyes? A grl.",
  "Where do birds stay when they travel? Someplace cheep.",
  "Why should you knock on your refrigerator door before opening it? There may be salad dressing in there.",
  "Did you hear about the worst zoo in the world? It only has one dog. It's a real shih tzu.",
  "What did one toilet say to the other? 'You appear a bit flushed.'",
  "Why are most people tired on April 1? They've just finished a 31-day March.",
  "How do you make a tissue dance? Put a little boogie in it.",
  "Why aren't lobsters generous? Because they're shellfish.",
  "Why did Mozart kill all of his chickens? When he asked who the best composer was, they all replied, 'Bach, Bach, Bach.'",
  "Why did the rabbit go to the salon? It was having a bad hare day.",
  "Why can't leopards play hide-and-seek? Because they're always spotted.",
  "How do you light up a sports stadium? With a soccer match.",
  "Where do sheep love to vacation? The Baa-hamas.",
  "Why did historians call the Early Middle Ages the Dark Ages? There were a lot of knights.",
  "Why did the employee go to work on stilts? He wanted a raise.",
  "What did one plate say to the other? 'Lunch is on me!'",
  "Why do comedians love telling jokes to ducks? They always quack up.",
  "How did the piano get locked out of its car? It lost its keys.",
  "What do you call a nose without a body? No body nose.",
  "How do you make an egg roll? You push it.",
  "Did you hear about the fire at the shoe factory? Unfortunately, many soles were lost.",
  "What kind of fish knows how to do an appendectomy? A sturgeon.",
  "How do you hire a horse? Stand it on a ladder.",
  "What did the fish say when he ran into a wall in the river? 'Dam!'",
  "Why do giraffes have long necks? Because they have stinky feet.",
  "Why did the pony ask for a glass of water? Because it was a little horse.",
  "Is there anything worse than when it's raining cats and dogs? Yes, hailing taxis.",
  "What do you call two doctors? Pair-a-medics.",
  "What did 0 say to 8? 'Nice belt.'",
  "I wondered why the baseball kept getting bigger. Then it hit me.",
  "Cremation. My final hope for a smokin' hot body.",
  "Before my friend Frank died, he asked that I store his ashes in his favorite beer mug. His last wish was to be Frank in stein.",
  "A man walks into an enchanted forest and tries to cut down a talking tree. 'You can't cut me down,' the tree exclaims. 'I'm a talking tree!' The man responds, 'You may be a talking tree, but you will dialogue.'",
  "Today, I asked my phone, 'Siri, why am I still single?' It activated the front-facing camera.",
  "The most corrupt CEOs are the ones who run pretzel companies. They're always so twisted.",
  "After the man who created the hokeypokey died, it took a while to get the body in the casket. They put his right foot in. They took his right foot out …",
  "When I told my date I worked with animals, she found it really sweet and asked more about my job. So I told her: 'I'm a butcher.'",
  "They say the surest way to a man's heart is through the stomach. But I find going through the rib cage a lot easier.",
  "Why is it that if you donate a kidney, people love you, but if you donate five kidneys, they call the police?",
  "Two cows were standing in a field. 'Have you heard that mad cow disease is going around?' asked the first. 'Yeah,' the other cow replied. 'Makes me glad I'm a penguin.'",
  "A termite walks into a bar and asks, 'Is the bar tender here?'",
  "A Roman walks into a bar, holds up two fingers and says, 'Five beers, please.'",
  "My three favorite things are eating my family and not using commas.",
  "A snake walks into a bar, and the bartender asks, 'How?'",
  "A dyslexic atheist lies awake at night wondering if there really is a dog.",
  "My colorblind diagnosis really came out of the orange.",
  "I wasn't originally going to get a brain transplant, but then I changed my mind.",
  "I entered 10 puns in a contest to see which would win. No pun in 10 did.",
  "A man walks into a bar and says, 'That's going to leave a mark.'",
  "My dog used to chase people on bikes a lot. It got so bad that finally I had to take his bike away.",
  "First, the doctor told me the good news. He said that I was going to have a disease named after me. —Steve Martin",
  "Never keep up with the Joneses. Drag them down to your level. It's cheaper. —Quentin Crisp",
  "Always forgive your enemies; nothing annoys them so much. —Oscar Wilde",
  "Give a man a fish, and he will eat for a day. Teach a man to fish, and he will sit in a boat and drink beer all day.",
  "A man went to see his doctor, and the doctor said, 'I have some bad news and some worse news.' The man asked for the bad news first, and the doctor replied, 'You have only 24 hours to live.' Gutted, the man said, 'That's terrible! What's the worse news?' The doctor responded, 'I should have told you yesterday.'",
  "What did one hat say to the other? You stay here. I'll go on ahead.",
  "Where do pirates get their hooks? Secondhand stores.",
  "Knock knock. Who's there? Boo. Boo who? Don't cry, I'm only joking!",
  "What did the pirate say when he turned 80? Aye matey.",
  "What do you call two birds in love? Tweethearts!",
  "Why did the picture go to jail? Because it was framed.",
  "What do you call a sad cup of coffee? Depresso.",
  "Irish puns are the most O'ffensive.",
  "I went to buy some camo pants but couldn't find any.",
  "Knock knock. Who's there? Adore. Adore who? Adore is between us, so please open up.",
  "How do you organize a space party? You planet.",
  "How did the telephone propose to his girlfriend? He gave her a ring.",
  "What do horses say when they fall? Help, I've fallen and I can't giddy up.",
  "If a parsley farmer gets sued, can they garnish his wages?",
  "Knock knock. Who's there? Candice. Candice who? Candice joke get any worse?",
  "What runs but never goes anywhere? A refrigerator.",
  "What do you call a beehive without an exit? Unbelievable.",
  "What did the cucumber say to the pickle? You mean a great dill to me.",
  "Why don't we see elephants hiding in trees? Because they're really good at it.",
  "6:30 is the best time on a clock, hands down.",
  "Which is faster, hot or cold? Hot, because you can catch a cold.",
  "What did the tomato say to the other tomato during a race? Ketchup.",
  "Knock, knock. Who's there? Iva. Iva who? I've a sore hand from knocking.",
  "What did one ocean say to the other ocean? Nothing, they just waved.",
  "If attacked by a mob of clowns, go for the juggler.",
  "Why can't you trust duck doctors? They're all quacks.",
  "Knock, knock. Who's there? Wooden shoe. Wooden shoe who? Wooden shoe like to hear another joke?",
  "What do you call a ghost's sweetheart? A ghoul-friend.",
  "Why can't a leopard hide? Because he's always spotted.",
  "The rotation of Earth really makes my day.",
];

let a = Math.floor(Math.random()*jokes.length);
let h = document.querySelector(".heading");
h.innerText = jokes[a];
console.log(jokes[a]);